### ISSUE TITLE
加速下落不彻底

### ISSUE THREAD

**Issue by KairuiLiu** [serendipityApe/tetris#1]
如图, 使用下键加速Z字形方块下落时无法彻底下落

---

![深度截图_选择区域_20220321001319](https://user-images.githubusercontent.com/25458969/159171882-1e53c0e7-e9b7-42f1-b25d-57a1372c40cf.png)

**Comment by serendipityApe** [comment]
感谢指出😃，问题已修复 #https://github.com/serendipityApe/tetris/commit/eafaa6281fc8076b8fab30be901223fe2bdb1a05
